SQL> CREATE TABLE RESERVATION
 (
 ReservationID INT NOT NULL,
 Pick_Up_Date DATE NOT NULL,
 Return_Date DATE NOT NULL,
 Daily_Rate DECIMAL(20,2) NOT NULL,
 Total DECIMAL(20,2) NOT NULL,
 CustomerID INT NOT NULL,
 RentalOfficeID INT NOT NULL,
 PRIMARY KEY (ReservationID),
 FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
 FOREIGN KEY (RentalOfficeID) REFERENCES RENTAL_OFFICE_LOCATION(RentalOfficeID)
 );
