SQL> CREATE TABLE VEHICLE
(
  VIN VARCHAR(30) NOT NULL,
  Make VARCHAR(30) NOT NULL,
  Model VARCHAR(30) NOT NULL,
  Year INT NOT NULL,
  Color CHAR(30) NOT NULL,
  LicensePlate VARCHAR(20) NOT NULL,
  Mileage INT NOT NULL,
  PRIMARY KEY (VIN),
  UNIQUE (LicensePlate)
  );
